# Generated by Django 3.1.4 on 2020-12-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='start_date',
            new_name='start',
        ),
    ]
