# Generated by Django 3.1.4 on 2021-01-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='holidays',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='holidays',
            name='day_of_week',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=255, null=True),
        ),
    ]
