# Generated by Django 3.1.4 on 2021-01-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(choices=[('1', 'Personal'), ('2', 'Sick'), ('3', 'Family'), ('4', 'Vacation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='secondary_email',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
    ]
