# Generated by Django 3.1.4 on 2020-12-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parentDepartment_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='Holidays',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
