# Generated by Django 3.1.4 on 2020-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flag',
            field=models.CharField(choices=[('1', 'Enabled'), ('0', 'Disabled')], max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
    ]
