# Generated by Django 3.1.4 on 2021-01-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210111_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='username',
        ),
    ]
