# Generated by Django 3.1.4 on 2021-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210119_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=255, null=True),
        ),
    ]
