# Generated by Django 3.1.4 on 2020-12-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201221_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='leave_days_left',
            new_name='leave_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='flag',
        ),
    ]
