# Generated by Django 3.1.4 on 2021-01-11 22:04

import application.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_systemuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='systemuser',
            managers=[
                ('objects', application.models.UserManager()),
            ],
        ),
    ]
