# Generated by Django 3.1.4 on 2020-12-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201228_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'role_id': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.userrole'),
        ),
    ]
