# Generated by Django 3.1.4 on 2021-01-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210111_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.CharField(default='ikub1234', max_length=255),
        ),
    ]
