# Generated by Django 3.1.4 on 2020-12-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201221_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default='      ', on_delete=django.db.models.deletion.CASCADE, to='application.department'),
        ),
    ]
