# Generated by Django 3.1.4 on 2020-12-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20201221_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='HOD', to='application.user'),
        ),
    ]
