# Generated by Django 3.1.4 on 2020-12-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_department_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parentDepartment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HOD', to='application.user'),
        ),
    ]
