# Generated by Django 3.1.4 on 2020-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201222_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role_id',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_id',
            field=models.ManyToManyField(to='application.Role'),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_id',
            field=models.ManyToManyField(to='application.User'),
        ),
    ]
