# Generated by Django 3.1.4 on 2020-12-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20201222_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='application.userrole'),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role_id',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.role'),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.user'),
        ),
    ]
