# Generated by Django 3.1.4 on 2020-12-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20201222_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.role'),
        ),
    ]
